
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADJETIVO ADVERBIO ARTICULO CONJUNCION CONTRACCION DESCONOCIDO INTERJECCION PREPOSICION PRONOMBRE PUNTUACION SUSTANTIVO VERBOsentence : subject predicate\n| subject predicate complement\n| interjection\n| sentence PUNTUACIONsubject : PRONOMBREsubject : ARTICULO SUSTANTIVOsubject : ARTICULO ADJETIVO SUSTANTIVOsubject : SUSTANTIVOpredicate : VERBOpredicate : VERBO complementpredicate : VERBO ADVERBIOpredicate : VERBO PRONOMBREcomplement : SUSTANTIVOcomplement : ARTICULO SUSTANTIVOcomplement : ADJETIVOcomplement : PREPOSICION ARTICULO SUSTANTIVOcomplement : PREPOSICION SUSTANTIVOcomplement : ADVERBIOinterjection : INTERJECCIONempty :'
    
_lr_action_items = {'PRONOMBRE':([0,10,],[4,21,]),'ARTICULO':([0,9,10,14,16,17,19,20,21,23,25,26,],[5,15,15,-13,-15,24,-10,-11,-12,-14,-17,-16,]),'SUSTANTIVO':([0,5,9,10,12,14,15,16,17,19,20,21,23,24,25,26,],[6,11,14,14,22,-13,23,-15,25,-10,-11,-12,-14,26,-17,-16,]),'INTERJECCION':([0,],[7,]),'$end':([1,3,7,8,9,10,13,14,16,18,19,20,21,23,25,26,],[0,-3,-19,-4,-1,-9,-2,-13,-15,-18,-10,-11,-12,-14,-17,-16,]),'PUNTUACION':([1,3,7,8,9,10,13,14,16,18,19,20,21,23,25,26,],[8,-3,-19,-4,-1,-9,-2,-13,-15,-18,-10,-11,-12,-14,-17,-16,]),'VERBO':([2,4,6,11,22,],[10,-5,-8,-6,-7,]),'ADJETIVO':([5,9,10,14,16,19,20,21,23,25,26,],[12,16,16,-13,-15,-10,-11,-12,-14,-17,-16,]),'PREPOSICION':([9,10,14,16,19,20,21,23,25,26,],[17,17,-13,-15,-10,-11,-12,-14,-17,-16,]),'ADVERBIO':([9,10,14,16,19,20,21,23,25,26,],[18,20,-13,-15,-10,-11,-12,-14,-17,-16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sentence':([0,],[1,]),'subject':([0,],[2,]),'interjection':([0,],[3,]),'predicate':([2,],[9,]),'complement':([9,10,],[13,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sentence","S'",1,None,None,None),
  ('sentence -> subject predicate','sentence',2,'p_sentence','app.py',111),
  ('sentence -> subject predicate complement','sentence',3,'p_sentence','app.py',112),
  ('sentence -> interjection','sentence',1,'p_sentence','app.py',113),
  ('sentence -> sentence PUNTUACION','sentence',2,'p_sentence','app.py',114),
  ('subject -> PRONOMBRE','subject',1,'p_subject_pronoun','app.py',123),
  ('subject -> ARTICULO SUSTANTIVO','subject',2,'p_subject_article_noun','app.py',129),
  ('subject -> ARTICULO ADJETIVO SUSTANTIVO','subject',3,'p_subject_article_adj_noun','app.py',136),
  ('subject -> SUSTANTIVO','subject',1,'p_subject_noun','app.py',144),
  ('predicate -> VERBO','predicate',1,'p_predicate_verb','app.py',150),
  ('predicate -> VERBO complement','predicate',2,'p_predicate_verb_complement','app.py',156),
  ('predicate -> VERBO ADVERBIO','predicate',2,'p_predicate_verb_adverb','app.py',164),
  ('predicate -> VERBO PRONOMBRE','predicate',2,'p_predicate_verb_pronoun','app.py',171),
  ('complement -> SUSTANTIVO','complement',1,'p_complement_noun','app.py',178),
  ('complement -> ARTICULO SUSTANTIVO','complement',2,'p_complement_article_noun','app.py',184),
  ('complement -> ADJETIVO','complement',1,'p_complement_adj','app.py',191),
  ('complement -> PREPOSICION ARTICULO SUSTANTIVO','complement',3,'p_complement_prep_article_noun','app.py',197),
  ('complement -> PREPOSICION SUSTANTIVO','complement',2,'p_complement_prep_noun','app.py',205),
  ('complement -> ADVERBIO','complement',1,'p_complement_adverb','app.py',212),
  ('interjection -> INTERJECCION','interjection',1,'p_interjection','app.py',218),
  ('empty -> <empty>','empty',0,'p_empty','app.py',224),
]
